name: Deploy Staging
on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deployCdk :
    name: Deploy CDK Staging
    environment: beta
    runs-on:
      - self-hosted
      - codebuild-x64
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      uses: actions/setup-node@v3
      with:
        node-version: 18
    -
      name: Authenticate Via OIDC Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-1
        role-duration-seconds: 1800
        role-skip-session-tagging: true
        role-to-assume: arn:aws:iam::727174507127:role/GitHubActionRole
    -
      name: Assume CDK Deploy Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ap-southeast-1
        role-duration-seconds: 1800
        role-skip-session-tagging: true
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        role-to-assume: arn:aws:iam::487053431871:role/cdk-hnb659fds-deploy-role-487053431871-ap-southeast-1
        role-external-id: Pipeline
    -
      name: Deploy with CDK
      run: |-
        cd .cdk
        npm ci
        npm run build
        npm run cdk synth
        npm run cdk deploy sotogubeng-Www/Pipeline/popbela-beta/* --require-approval never
